adminlteui/models.py
# -*- coding: utf-8 -*-
import itertools
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.models import ContentType

from treebeard.mp_tree import MP_Node,\
    InvalidMoveToDescendant, MP_MoveHandler


class Options(models.Model):
    option_name = models.CharField(
        max_length=255, unique=True, verbose_name=_('Option Name'))
    option_value = models.TextField(
        verbose_name=_('Option Value'))
    valid = models.BooleanField(default=True, verbose_name=_('Valid'))
    create_time = models.DateTimeField(
        default=timezone.now, verbose_name=_('CreateTime'))
    update_time = models.DateTimeField(
        auto_now=True, verbose_name=_('UpdateTime'))

    def __str__(self):
        return '{}'.format(self.option_name)

    class Meta:
        verbose_name = _('Options')
        verbose_name_plural = _('All Options')


class Menu(MP_Node):
    LINK_TYPE = (
        (0, _('Internal')),
        (1, _('External')),
        (3, _('Divide'))
    )
    name = models.CharField(max_length=255, verbose_name=_('name'))
    position = models.CharField(
        max_length=255, default='left', verbose_name=_('Menu Position'))
    link_type = models.IntegerField(default=0, choices=LINK_TYPE,
                                    verbose_name=_('Link Type'))
    link = models.CharField(max_length=255, blank=True, null=True,
                            verbose_name=_('Link'),
                            help_text=_(
                                'support admin:index or /admin/ or http://'))
    icon = models.CharField(max_length=255,
                            blank=True,
                            null=True,
                            verbose_name=_('Icon'))
    content_type = models.ForeignKey(ContentType,
                                     blank=True, null=True,
                                     verbose_name=_('ContentType'),
                                     on_delete=models.CASCADE,
                                     help_text=_(
                                         'use for permission control.'))
    priority_level = models.IntegerField(default=100,
                                         verbose_name=_('Priority Level'),
                                         help_text=_('The bigger the priority'))
    valid = models.BooleanField(default=True, verbose_name=_('Valid'))
    node_order_by = ['priority_level']

    def move(self, target, pos=None):
        """
        Moves the current node and all it's descendants to a new position
        relative to another node.

        :raise PathOverflow: when the library can't make room for the
           node's new position
        """
        if target.depth == 2:
            raise InvalidMoveToDescendant(_('max depth is 2.'))
        return MP_MoveHandler(self, target, pos).process()

    def __str__(self):
        return '{}|{}'.format(self.name, self.priority_level)

    class Meta:
        verbose_name = _('Menu')
        verbose_name_plural = _('Menu Setting')

adminlteui/__init__.py
version = '1.5.0b0'
default_app_config = 'adminlteui.apps.AdminlteUIConfig'

adminlteui/templates/adminlte/form.html
{% for field in form %}
<div class="row">
    <label class="col-sm-2 control-label text-right">
        {{ field.field.label }}
    </label>
    <div class="col-sm-7">
        {% if field.is_readonly %}
        <div class="readonly" style="margin-top: 7px;">{{ field.contents }}</div>
        {% else %}
        {{ field }}
        {% endif %}
        {% if field.field.help_text %}
        <div class="help-block">{{ field.field.help_text|safe }}</div>
        {% endif %}
    </div>
    <div class="col-sm-3">
        <div class="help-block text-red">
            {% if not field.fields|length_is:'1' and not field.is_readonly %}{{ field.errors }}{% endif %}
        </div>
    </div>
</div>
{% endfor %}

adminlteui/templates/adminlte/general_option.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static adminlte_options %}

{% block extrastyle %}
{{ block.super }}
<link rel="stylesheet" href="{% static "admin/dist/css/app.css" %}">
{% endblock %}


{% block breadcrumbs %}
<ol class="breadcrumb">
    <li><a href="{% url 'admin:index' %}"><i class="fa fa-dashboard"></i> {% trans 'Home' %}</a></li>
    <li><a href="javascript:void(0)">{% trans 'AdminSettings' %}</a></li>
    <li class="active">{% trans 'General Option' %}</li>
</ol>
{% endblock %}

{% block title %}{% trans 'General Option' %} |
{% get_adminlte_option 'site_title' as adminlte_site_title %}
{% if adminlte_site_title.valid %}
{{ adminlte_site_title.site_title }}
{% else %}
{{ site_title|default:_('Django site admin') }}
{% endif %}
{% endblock %}

{% block content_title %} {% trans 'General Option' %} {% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h4 class="box-title">
                    {% trans 'General Option' %}
                </h4>
            </div>

            <div class="box-body">
                <div id="content-main">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'adminlte/form.html' with form=line %}
                        <div class="row">
                            <div class="submit-row col-md-12 col-md-push-2">
                                <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <br class="clear" />
    </div>
</div>
{% endblock %}


{% block extrajs %}
<script>
    $('[required]').before('<span class="text-red" style="margin-left: -10px;">* </span>');
</script>
{% endblock %}

adminlteui/templates/adminlte/menu_change_form.html
{% extends 'admin/change_form.html' %}

{% block extrajs %}
{{ block.super }}

<script>
    django.jQuery('#id_content_type').select2();
    $.fn.link_type = function () {
        $(this).change(function () {
            var $field = $(this);
            var $option = $field.find('option:selected');
            if ($option.val() !== "0") {
                $('.field-content_type').hide();
            } else {
                $('.field-content_type').show();
            }
            if ($option.val() === "3") {
                $('.field-link').hide();
            } else {
                $('.field-link').show();
            }
        });
        $(this).trigger('change');
    };
    $('#id_link_type').link_type();
</script>
{% endblock %}

adminlteui/templates/adminlte/menu_change_list.html
{# Used for MP and NS trees #}
{% extends "admin/change_list.html" %}
{% load admin_list admin_tree adminlte_list i18n %}

{% block extrastyle %}
{{ block.super }}
{% treebeard_css %}
{% endblock %}

{% block extrahead %}
{{ block.super }}
{% treebeard_js %}
{% endblock %}

{% block object-tools-items %}
<button id="exchange_menu" class="btn btn-danger">{% trans 'Exchange Menu' %}</button>
{{ block.super }}
{% endblock %}

{% block result_list %}
{% if action_form and actions_on_top and cl.full_result_count %}
{% admin_actions %}
{% endif %}
{% adminlte_result_tree cl request %}
{% if action_form and actions_on_bottom and cl.full_result_count %}
{% admin_actions %}
{% endif %}
{% endblock %}

{% block extrajs %}
{{ block.super }}
<script>
    $(function () {
        $('#exchange_menu').click(function () {
            $.get('{% url "admin:exchange_menu" %}', function (response) {
                console.log(response);
                if (response.message === 'success') {
                    window.location.reload();
                }
            })
        })
    });
</script>
{% endblock %}

adminlteui/templates/adminlte/widgets/select.html
<select name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
<optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
    {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
</optgroup>{% endif %}{% endfor %}
</select>
<script>django.jQuery('#id_{{widget.name}}').select2()</script>